spring:
  application:
    name: ingestion-service
  datasource:
    url: jdbc:postgresql://postgres:5432/pulsehub
    username: pulsehub
    password: pulsehub
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    consumer:
      bootstrap-servers: kafka:29092
      group-id: ingestion-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.protobuf.KafkaProtobufDeserializer
      properties:
        schema.registry.url: http://schema-registry:8081
        specific.protobuf.value.type: com.pulsehub.common.proto.UserActivityEvent

server:
  port: 8083

application:
  kafka:
    topics:
      user-activity: user-activity-events

pulsehub:
  kafka:
    topic: user-activity-events 