spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:postgres}:${POSTGRES_PORT:5432}/${POSTGRES_DB:pulsehub}
    username: ${POSTGRES_USER:pulsehub}
    password: ${POSTGRES_PASSWORD:pulsehub}
  kafka:
    consumer:
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:29092}
      properties:
        schema.registry.url: ${SCHEMA_REGISTRY_URL:http://schema-registry:8081}

server:
  port: ${INGESTION_SERVICE_PORT:8083}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://eureka:8761/eureka}
  instance:
    prefer-ip-address: true
