spring:
  config:
    activate:
      on-profile: docker

  datasource:
    url: jdbc:postgresql://postgres:5432/pulsehub
    username: pulsehub
    password: pulsehub

  data:
    redis:
      host: redis
      port: 6379

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka
  instance:
    hostname: profile-service
    prefer-ip-address: true
