server:
  port: "${PROFILE_SERVICE_PORT:8084}" # Port for the profile service

spring:
  application:
    name: profile-service
  datasource:
    url: "jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:pulsehub_db}"
    username: "${POSTGRES_USER:pulsehub}"
    password: "${POSTGRES_PASSWORD:pulsehub}"
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update # Automatically update the schema
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect 
  data:
    redis:
      host: "${REDIS_HOST:redis}"
      port: "${REDIS_PORT:6379}"

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus  # 暴露 health 和 prometheus 端点(为未来监控做准备)
  endpoint:
    health:
      show-details: always

# ... existing code ... 