spring:
  application:
    name: infrastructure-service
  profiles:
    active: "${SPRING_PROFILES_ACTIVE:local}"  # 默认本地
  kafka:
    bootstrap-servers: "${KAFKA_BOOTSTRAP_SERVERS:kafka:29092}"
    admin:
      request-timeout: 30000
      connections-max-idle: 300000
      retry-backoff: 1000
    producer:
      bootstrap-servers: "${KAFKA_BOOTSTRAP_SERVERS:kafka:29092}"
      properties:
        partitioner.class: com.pulsehub.infrastructure.kafka.partitioner.TopicAwarePartitioner

  datasource:
    url: "jdbc:postgresql://${POSTGRES_HOST:postgres}:${POSTGRES_PORT:5432}/${POSTGRES_DB:pulsehub}"
    username: "${POSTGRES_USER:pulsehub}"
    password: "${POSTGRES_PASSWORD:pulsehub}"
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 2
      minimum-idle: 1
      connection-timeout: 5000
      validation-timeout: 3000

  data:
    redis:
      host: "${REDIS_HOST:redis}"
      port: "${REDIS_PORT:6379}"
      timeout: 3000ms
      connect-timeout: 3000ms
      jedis:
        pool:
          max-active: 2
          max-wait: 3000ms
          max-idle: 2
          min-idle: 1

server:
  port: "${INFRASTRUCTURE_SERVICE_PORT:8085}"

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: "${EUREKA_URI:http://localhost:8761/eureka}"
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
    lease-renewal-interval-in-seconds: 30
    prefer-ip-address: true

pulsehub:
  discovery:
    enabled: true

app:
  environment: "${APP_ENVIRONMENT:dev}"

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics
  endpoint:
    health:
      show-details: always
  health:
    kafka:
      enabled: true
    redis:
      enabled: true
    db:
      enabled: true

logging:
  level:
    com.pulsehub.infrastructure: INFO
    org.apache.kafka: WARN
    org.springframework.kafka: INFO
    org.springframework.boot.actuate: INFO
    org.springframework.cloud.netflix.eureka: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
